### ISSUE TITLE
Text color and position

### ISSUE THREAD

**Issue by chvk25** [kurkle/chartjs-chart-treemap#1]
is there a way to change the color and position of text in groups.

**Comment by dannylonglegs** [comment]
Bump.

I can't figure out a way to style the labels that appear from the `groups` array in datasets. They default to what looks like "12px serif" and can not be changed.

Thanks

**Comment by connerbw** [comment]
Team bump. 

Could this be a configurable option?

https://github.com/kurkle/chartjs-chart-treemap/blob/d01f0151c4ac743046f16463d54895c37ffcea7b/src/controller.js#L149

 Or a better idea?

**Comment by dcworldwide** [comment]
This lib is awesome. Thanks!

Also looking for a solution

**Comment by kurkle** [comment]
Only just noticed this issue 😞 
I've released 0.2.2 that allows changing font options. Position remains fixed, how would you like that to be configurable?

**Comment by developerazharshaikh** [comment]
@chvk25 I was trying to implement treemap with chartjs-node-canvas
and I get this error

TypeError: Cannot read property 'hidden' of null
errorHandler.js:14
message:"Cannot read property 'hidden' of null"
stack:"TypeError: Cannot read property 'hidden' of null\n    at updateMinMax (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:12964:60)\n    at ChartElement.determineDataLimits (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:13001:5)\n    at ChartElement.update (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:11502:6)\n    at fitBoxes (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:7127:7)\n    at Object.update (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:7338:3)\n    at Chart.updateLayout (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:9680:16)\n    at Chart.update (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:9633:6)\n    at Chart.construct (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:9357:6)\n    at new Chart (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:9294:7)\n    at CanvasRenderService.renderChart (d:\Probench\ChartServices\node_modules\chartjs-node-canvas\dist\index.js:150:16)...
