### ISSUE TITLE
Chart is shown with single color

### ISSUE THREAD

**Issue by arunreghu** [kurkle/chartjs-chart-treemap#10]
Chart is showing with single color (blue). Not showing with different gradients.
Please check your code in https://codepen.io/kurkle/full/JqbzgQ

 backgroundColor: function(ctx) {
                var value = ctx.dataset.data[ctx.dataIndex];
                var alpha = (value + 3) / 10;
                return Color('blue').alpha(alpha).rgbString();
            }
variable alpha is NaN .

This function always returns the same RGB value rgb(0, 0, 255)

**Comment by kurkle** [comment]
Sample fixed
