### ISSUE TITLE
borderRadius?

### ISSUE THREAD

**Issue by hisenberg1** [kurkle/chartjs-chart-treemap#103]
Is there a way to have the treemap boxes drawn with rounded corners (borderRadius).
The ChartJS barChart has a borderRadius option (https://www.chartjs.org/docs/latest/charts/bar.html#borderradius). 
It would give the treemap a nice modern look.
Thank you.

**Comment by stockiNail** [comment]
This new enhancement could be in conflict with the `borderWidth` option set as object. The quickest way to implement it could be that when the `borderWidth` is set as object, the `borderRadius` will be ignored.
@kurkle what do you think?
