### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by queenvictoria** [kurkle/chartjs-chart-treemap#109]
Hi there apologies for this. I'm trying to integrate the package into an existing project which is causing errors.

To debug I am trying to run the package locally with `npm link`. Ahead of that I'm trying to run the test harness. I notice it fails in a few ways--it seems to be linting and the karma browser control (at first run at least). I'm not familiar with karma BTW. Also this is on Ubuntu.

The steps I've been using:
```bash
$ # git clone etc.
$ nvm use 18 # or 16 or 14
$ npm install
$ npm run build # or not
$ npm test 
$ # many errors with eslint and karma + Chrome and Firefox--do I need to install something else here?
$ npm run lint # Same as above: lots of linting errors
```

I must be missing something. Any thoughts?

**Comment by kurkle** [comment]
You are probably hitting the issue with karma-rollup-preprocessor 7.0.8 that was just fixed on the side of another PR.
The 7.0.8 version of the preprocessor overwrites test files with garbage.

Then there is the possibility of failures with fixtures containing text (I get a lot of those on my mac). You can just ignore those for now.

**Comment by stockiNail** [comment]
@queenvictoria the PR #107 fixed the issue of karma-rollup-preprocessor, therefore using that issue should be fixed. For fixtures, another PR should be raised to change all test cases using spriting.

**Comment by queenvictoria** [comment]
Thank you @kurkle @stockiNail ! That fixes the testing for me.
