### ISSUE TITLE
How to show lables in basic treemap

### ISSUE THREAD

**Issue by arunreghu** [kurkle/chartjs-chart-treemap#11]
![rsz_screenshot_from_2020-07-06_18-33-46](https://user-images.githubusercontent.com/20110524/86596237-85a00a80-bfb7-11ea-8851-d03242de1511.png)

How show labels in your basic treemap with different color opacity like the image above?

**Comment by kurkle** [comment]
Not sure what you are asking. The color scale at the bottom?

**Comment by arunreghu** [comment]
No, I mean the labels in the chart (Airport, Bridge.Gas.. etc). If we can include the color scale that is fine. I am trying to replicate the above chart in our charts treemap.

**Comment by kurkle** [comment]
You need to have `key`, `groups` and `fontColor` defined for the dataset.
Added asample in https://codepen.io/kurkle/pen/JqbzgQ?editors=1010

**Comment by arunreghu** [comment]
One problem is remaining is color. Now it shows a single color in the whole chart.

**Comment by kurkle** [comment]
```js
        backgroundColor: function(ctx) {
          return colorFromValue(ctx.dataset.data[ctx.dataIndex].v);
        },
```

**Comment by arunreghu** [comment]
@kurkle  it throws an error TypeError: Cannot read property 'v' of undefined 
I have created a codepen for you can you take a look?
https://codepen.io/arunreghu/pen/mdVxRbv?editors=1111

**Comment by kurkle** [comment]
Its due to chart.js asking the backgroundColor before the data is populated.

https://codepen.io/kurkle/pen/LYGdxpr

**Comment by arunreghu** [comment]
It worked, Thank you so much @kurkle  for your valuable time.
