### ISSUE TITLE
VueJS/NextJS: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by queenvictoria** [kurkle/chartjs-chart-treemap#110]
Hi there. This is the issue I was trying to debug in my local. The tests pass locally but still were throwing an error. So I've replicated it in this sandbox:
https://codesandbox.io/s/eloquent-bardeen-fyi1cv?file=/pages/index.vue

Can you see what's going wrong? Have I done something silly?

**Comment by stockiNail** [comment]
I had a look to the sandbox but it seems correct. It's weird to see the error in `isForType` method which is an internal of CHART.JS core. Probably it also depends on my lack of knowledge in VueJS/NextJS.

**Comment by queenvictoria** [comment]
Thanks @stockiNail . If I remove the treemap module the error goes away and I can draw other kinds of charts. I'll see if I can import other controllers.

Without other controllers Chart JS works fine:
https://codesandbox.io/s/xenodochial-thunder-dih73f?file=/pages/index.vue

Graph controllers has the same issue as treemap:
https://codesandbox.io/s/modest-julien-lmhrf4?file=/pages/index.vue

 I'll dig in.

**Comment by queenvictoria** [comment]
Ok moving the register call into the mounted hook resolves the issue for me. This is [derived from a comment](https://github.com/chartjs/chartjs-plugin-annotation/issues/216#issuecomment-754614044) about React needing the DOM element to exist (the ref created) before registering the component.

_FAILS_
```javascript
import { Chart, LinearScale } from "chart.js";
import { TreemapController, TreemapElement } from "chartjs-chart-treemap";
Chart.register(LinearScale, TreemapController, TreemapElement);

export default {
  data() {
    return {
      // Data that will hold the Chart.js instance.
      chart: null,
    };
  },

  mounted() {
    const config = {...}
  }
}
```

_SUCCEEDS_
```javascript
import { Chart, LinearScale } from "chart.js";
import { TreemapController, TreemapElement } from "chartjs-chart-treemap";

export default {
  data() {
    return {
      // Data that will hold the Chart.js instance.
      chart: null,
    };
  },

  mounted() {
    Chart.register(LinearScale, TreemapController, TreemapElement); // <---- moved to after mounted
    const config = {...}
  }
}
```

**Comment by stockiNail** [comment]
@queenvictoria thank you very much for your feedbacks! Very helpful for me who am not so familiar with VUEJS and NEXTJS
