### ISSUE TITLE
How to show both  tittle and  value in treemap?

### ISSUE THREAD

**Issue by arunreghu** [kurkle/chartjs-chart-treemap#12]
tree: [{value: 100, title: 'Alpha'}, {value: 20, title: 'Beta'}, {value: 5, title: 'Gamma'}],
Your current implementation its only show title.
I want to show both title and value in treemap how to do that? Also if the title has a long text it will not fit it UI so how to wrap that text?

**Comment by kurkle** [comment]
Duplicate of #7
