### ISSUE TITLE
Export with chartjs-node-canvas

### ISSUE THREAD

**Issue by bryandandan** [kurkle/chartjs-chart-treemap#13]
Hello,

Is **chartjs-chart-treemap** exportable with the infamous node wrapper **chartjs-node-canvas**?

Thanks

**Comment by kurkle** [comment]
I don't know any reason fot it not to work.

**Comment by bryandandan** [comment]
chartjs node-canvas only supports native chart.js charts (non-exentions charts). chartjs-chart-treemap is an extension chart. This is the list of currently supported charts: bar, bubble, doughnut, horizontalBar, line, polarArea, pie, radar, scatter

**Comment by kurkle** [comment]
Right. You should be able to use it with node-canvas (or one of the variants that works)

**Comment by bryandandan** [comment]
As explained in my previous comment, node-canvas doesn't seem to export extensions. it only supports regular chart js charts.

**Comment by kurkle** [comment]
Not sure what you are taking about.
https://github.com/SeanSobey/ChartjsNodeCanvas
Seems to support extensions. However I was referring to using 
https://github.com/Automattic/node-canvas or some other canvas implementation for node that does not have any knowledge about chart.js (and thus no limitations on how to use it with chart.js).

**Comment by bryandandan** [comment]
Oh ok. Thank you for clarifying that there are 2 node-canvas. I will look into the second one
