### ISSUE TITLE
Issue when using treemap WITHOUT using chartjs-datalabels, but other graphs do

### ISSUE THREAD

**Issue by jsebsd** [kurkle/chartjs-chart-treemap#14]
I was having issues with my treemap not rendering properly and causing the other charts (that use datalabels) on the page to render incorrectly. 
The problem was that chartjs-datalabels is not opt in, so you have to specify the following if you want to use a treemap w/o using the datalabels plugin :

`plugins: {
  datalabels: {
    display : false 
}}`

Leaving this here to help others who encounter this problem.

**Comment by kurkle** [comment]
Thanks,

Note that `plugins: { datalabels: false }` is the [documented way](https://www.chartjs.org/docs/latest/developers/plugins.html#disable-plugins) of disabling plugin per chart.

**Comment by kurkle** [comment]
This is now mentioned on the README.
