### ISSUE TITLE
How to add the chartjs-plugin-zoom plugin plugin?

### ISSUE THREAD

**Issue by stockiNail** [kurkle/chartjs-chart-treemap#140]
### Discussed in https://github.com/kurkle/chartjs-chart-treemap/discussions/139

<div type='discussions-op-text'>

<sup>Originally posted by **mirzaeianfar** October  9, 2022</sup>
I can not add chartjs-plugin-zoom to treemap chart
Please help me</div>

**Comment by mirzaeianfar** [comment]
Thank you so much
