### ISSUE TITLE
Buttons inside of treemap squares

### ISSUE THREAD

**Issue by GrandMagus02** [kurkle/chartjs-chart-treemap#153]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/57040793/196385930-7035641c-18bf-49ee-8665-942f8db22973.png">
Is it possible to make buttons inside of blocks? Or maybe possibility to draw own box content?

**Comment by stockiNail** [comment]
> Is it possible to make buttons inside of blocks? Or maybe possibility to draw own box content? 

Not possible out of the box but you create a plugin to do both cases. With a plugin, you could raw whatever you what on the chart.
