### ISSUE TITLE
Not able to create treemap

### ISSUE THREAD

**Issue by Shriniket33** [kurkle/chartjs-chart-treemap#167]
Uncaught SyntaxError: Cannot use import statement outside a module
chartjs-adapter-date-fns.bundle.js:6225 Uncaught TypeError: Cannot read properties of undefined (reading '_adapters')
    at chartjs-adapter-date-fns.bundle.js:6225:10
    at chartjs-adapter-date-fns.bundle.js:4:76
    at chartjs-adapter-date-fns.bundle.js:5:2
chartjs-chart-treemap.js:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
chartjs-chart-treemap.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'helpers')
    at chartjs-chart-treemap.js:10:149
    at chartjs-chart-treemap.js:11:2
basic.html:33 Uncaught ReferenceError: Chart is not defined
    at HTMLScriptElement.<anonymous> (basic.html:33:27)

After changing type to module 

Uncaught SyntaxError: Cannot use import statement outside a module
chartjs-adapter-date-fns.bundle.js:6225 Uncaught TypeError: Cannot read properties of undefined (reading '_adapters')
    at chartjs-adapter-date-fns.bundle.js:6225:10
    at chartjs-adapter-date-fns.bundle.js:4:76
    at chartjs-adapter-date-fns.bundle.js:5:2
chartjs-chart-treemap.js:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
chartjs-chart-treemap.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'helpers')
    at chartjs-chart-treemap.js:10:149
    at chartjs-chart-treemap.js:11:2
basic.html:33 Uncaught ReferenceError: Chart is not defined
    at HTMLScriptElement.<anonymous> (basic.html:33:27)

**Comment by stockiNail** [comment]
@Shriniket33 can you provide a sample in order to reproduce the issue?

**Comment by Shriniket33** [comment]
The sample from your repository is what I am trying. You may check with the same.

**Comment by stockiNail** [comment]
@Shriniket33 thank you very much for feedback! The "samples" directory is not maintained and it should be removed (@kurkle what do you think?). Go to the documentation to have a look for samples: https://chartjs-chart-treemap.pages.dev/samples/basic.html

**Comment by Shriniket33** [comment]
Thank you. Will work on documentation provided.

**Comment by kurkle** [comment]
Updated the chart.js link in old samples, those might also work now.

**Comment by Shriniket33** [comment]
Thanks
