### ISSUE TITLE
Missing version 2.3.0 on NPM

### ISSUE THREAD

**Issue by stockiNail** [kurkle/chartjs-chart-treemap#176]
I think there is an issue in package.json because is still reporting the old version (2.2.0), instead of 2.3.0:

https://github.com/kurkle/chartjs-chart-treemap/blob/7fa38e21f6ce4ae471ed4dedaf77c62935c1a0fd/package.json#L4

I have feeling we didn't bump.

**Comment by kurkle** [comment]
fixed by fe3e48d318cd7aa686dc32ad42ec4330de458f66
