### ISSUE TITLE
Setup on server side 

### ISSUE THREAD

**Issue by developerazharshaikh** [kurkle/chartjs-chart-treemap#2]
I was trying to implement treemap with chartjs-node-canvas
and I get this error

    ```
"canvas": "^2.1.0",
    "chart.js": "^2.7.2",
    "chartjs-chart-treemap": "^0.2.2",
    "chartjs-node-canvas": "^2.0.0",
```
`TypeError: Cannot read property 'hidden' of null
errorHandler.js:14
message:"Cannot read property 'hidden' of null"
stack:"TypeError: Cannot read property 'hidden' of null\n at updateMinMax (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:12964:60)\n at ChartElement.determineDataLimits (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:13001:5)\n at ChartElement.update (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:11502:6)\n at fitBoxes (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:7127:7)\n at Object.update (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:7338:3)\n at Chart.updateLayout (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:9680:16)\n at Chart.update (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:9633:6)\n at Chart.construct (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:9357:6)\n at new Chart (d:\Probench\ChartServices\node_modules\chart.js\dist\Chart.js:9294:7)\n at CanvasRenderService.renderChart (d:\Probench\ChartServices\node_modules\chartjs-node-canvas\dist\index.js:150:16)...`

**Comment by kurkle** [comment]
Probably needs to be chart.js 2.8.0 or later

**Comment by kurkle** [comment]
Closing as inactive
