### ISSUE TITLE
Live examples borked

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [kurkle/chartjs-chart-treemap#21]
It seems that the live examples link is not working. I've had the page opened for a couple hours and nothing and after peeking into dev tools console:
![image](https://user-images.githubusercontent.com/11082362/111351421-72375a00-8683-11eb-8842-9242c4897447.png)

Could be backwards compatibility issues because you're using chartjs@next in the codepen example?

**Comment by kurkle** [comment]
Yes, this extension needs an update.

**Comment by kurkle** [comment]
Fixed with release of beta.4 (some caches need to update before @next returns that to codepen)
