### ISSUE TITLE
Live Example it's maybe outdated

### ISSUE THREAD

**Issue by sviluppo** [kurkle/chartjs-chart-treemap#22]
Hello first at all, nice work adding this chart type, thank you.

Currently seems impossible to change color font on this example (https://codepen.io/kurkle/pen/oNjXJwe?editors=1010)
Using `fontColor` or `font: { color: ...}` it's the same, doesn't work.

To make it work i had to `npm install --beta --save`.
I tried this after founding this example (https://codepen.io/kurkle/pen/LYGdxpr?editors=1010) on one of your closed issue.

**Now i'm trying to add also the value on the square but without success.**

I also had trouble with tooltip because as default was giving me `undefined: value` instead of `titleValue: value`.
I had to use the code that is in the last link:

`    tooltips: {
      callbacks: {
        title: function (item, data) {
          return data.datasets[item[0].datasetIndex].key;
        },
        label: function (item, data) {
          var dataset = data.datasets[item.datasetIndex];
          var dataItem = dataset.data[item.index];
          return dataItem.v;
        }
      }
    }` 
    
 Thank you!

**Comment by kurkle** [comment]
I've published new docs with samples couple of weeks ago and removed the link to codepen.
Having the samples in same repository makes it easier to keep them up to date.

So I think this should be resolved by that.
https://chartjs-chart-treemap.pages.dev/samples/basic.html

The font color is just `color`, not nested under `font`, because its not really a font property and that is consistent on how its configured in Chart.js v3 in general.

**Comment by sviluppo** [comment]
Thank you for the page with example, in your example **color** is now working good.
I tried to remove the version that i'm using (`^0.2.3`) and reinstall the package with `^1.0.0` but i have no luck.

Currently i was using `let chartTreemap = import('chartjs-chart-treemap');`
But now this give me an error:

`Module not found: Error: Can't resolve 'chart.js/helpers' in `'/home/alberto/PhpstormProjects/ram-backend/node_modules/chartjs-chart-treemap/dist'`


Can you implement into the doc  an example of integration with Angular?? 

I tried your example of integration but are not working in my case.

I also suggest you to add the link to the new docs into the **readme.md**.

Thank you! :muscle:

**Comment by kurkle** [comment]
@sviluppo alas, I've yet to create my first Angular project, so no, I don't think I can be of much help.

Anyway, you should make sure you are using Chart.js ^3.0.0 with 1.0.0 of chartjs-chart-treemap.

If you are using ng2-charts as a wrapper, you can probably get help from people out there.

The next line in rollup config might have relevance to the helpers error:
https://github.com/kurkle/chartjs-chart-treemap/blob/00f5d37e95b0430c944e6da54bebb6fafa6ea02f/rollup.config.js#L21

Not quite sure how to define that in an angular project.

The docs are linked in readme using a badge, that might have eluded you? :)

**Comment by sviluppo** [comment]
I will find a way and i will post you the solution just for future reader.
I'm not using ng2-charts i directly use 
`import Chart from 'chart.js';`

Thank you for your help! :D 

Yeah docs badge completely eluded me!  2 fast 2 furious :D

**Comment by kurkle** [comment]
Closing as the original issue is resolved. Feel free to comment here or create a PR for example usage in Angular.
