### ISSUE TITLE
Is there any ETA for a release that includes the groups fix?

### ISSUE THREAD

**Issue by jagobagascon** [kurkle/chartjs-chart-treemap#237]
I was trying to create a grouped chart, but no matter what I did it was not working. Then I found the bug (#181) was fixed more than a year ago and it hasn't been released yet. Is there any ETA for the next release?

Thank you

**Comment by kurkle** [comment]
I've just forgotten to do a release. I'll try and get one out today.

**Comment by kurkle** [comment]
https://github.com/kurkle/chartjs-chart-treemap/releases/tag/v2.3.1

**Comment by jagobagascon** [comment]
Superb! Thank you so much!
