### ISSUE TITLE
_datasetIndex is not set

### ISSUE THREAD

**Issue by dbarzin** [kurkle/chartjs-chart-treemap#25]
The current datasetIndex is always zero.

  options: {
    onClick: function (event, array) {  
       var active = window.treemap.getElementAtEvent(event);
       console.log(active[0]._datasetIndex);
      },

**Comment by kurkle** [comment]
Do you have an example where you'd expect it to be something else?

**Comment by dbarzin** [comment]
Here is a test case:

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-chart-treemap@0.2.3"></script>
        <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
     <body>
    <div style="width: 1000px; height: 500px;">
      <canvas id="treemap_chart_div"></canvas>
    </div>
    <script type="text/javascript">
    var topTags = [
     {group:"A", tag:"A1", num:10, url:"https//server/A1" },
     {group:"A", tag:"A1", num:12, url:"https//server/A2" },
     {group:"B", tag:"B1", num:4, url:"https//server/B1" },
     {group:"B", tag:"B2", num:5, url:"https//server/B2" },
     {group:"B", tag:"B3", num:6, url:"https//server/B3" },
     {group:"B", tag:"B4", num:5, url:"https//server/B4" },
     {group:"B", tag:"B5", num:3, url:"https//server/B5" },
     {group:"B", tag:"B6", num:4, url:"https//server/B6" },
     {group:"B", tag:"B7", num:5, url:"https//server/B7" },
     {group:"C", tag:"C1" , num:3, url:"https//server/C1" },
     {group:"C", tag:"C2", num:7, url:"https//server/C2" },
     {group:"C", tag:"C3" , num:4, url:"https//server/C3" },
     {group:"C", tag:"C4" , num:6, url:"https//server/C4" },
     {group:"C", tag:"C5" , num:5, url:"https//server/C5" },
     {group:"C", tag:"C6" , num:8, url:"https//server/C6" },
  ];

var ctx = document.getElementById("treemap_chart_div").getContext("2d");

var cnf = {
  type: "treemap",
  data: {
    datasets: [{
      tree: topTags,
      key: "num",
      groups: ['group','tag'],
    }]
  },
  options: {
    tooltips: { enabled: false },    
    onClick: function (event, array) {  
       var active = window.treemap.getElementAtEvent(event);
       // does not work -> datasetIndex is not set -> no click on treemap
       // console.log(active[0]._datasetIndex);
       // window.location=cnf["data"]["datasets"][active[0]._datasetIndex]["url"];
      },        
    hover: {
        onHover: function(e, el) {
          $("#treemap_chart_div").css("cursor", el[0] ? "pointer" : "default");
          }
        }
    }
  };
    window.onload = function() {
      window.treemap=new Chart(ctx, cnf);
    };
</script>
</body>
</html>

**Comment by kurkle** [comment]
The _datasetIndex is correctly 0, because you only have one dataset (treemap only supports one).
You should use the provoded `array` or `active` as I'd name the argument. It countains array of the elements under the mouse on click.
Multiple elements, because the groups are elements too.

So then you just find the one that is top one and use the url from that. The _index does not point to `tree`, but to the generated `data`.

https://codepen.io/kurkle/pen/yLMMvRJ

**Comment by dbarzin** [comment]
Thanks a lot for your answer !
Didier

**Comment by dbarzin** [comment]
closed
