### ISSUE TITLE
Can't focus/mouse-over only on the last-level block

### ISSUE THREAD

**Issue by pavitrakumar78** [kurkle/chartjs-chart-treemap#3]
Hi,

First, Thanks for writing this plugin. 

I'm experiencing a bug where when I mouse over/hover over a particular block, in some parts of the block, the lower-level's info is also shown. 
Example as gif: 
![treemapbug](https://user-images.githubusercontent.com/5354407/75364352-9a6de280-58e1-11ea-983f-d82f28d4cf66.gif)
(Source of code: https://codepen.io/kurkle/full/JqbzgQ)
When I mouse over CA block, I see not only CA, but also "West" and "Pacific" tooltip infos. 
Is this because the info passed to the tooltip function needs more processing to differentiate between the levels? It's basically like the blocks are overlapping but the overlap is not visible. But this is not present in blocks where the size is relatively small.

**Comment by kurkle** [comment]
It defaulted to the rectangle which's center was closest to the mouse.
I altered the default behavior to return all rects under the mouse.
v0.2.3 released and pen updated!
