### ISSUE TITLE
How to use this plugin with react-chartjs-2 (chartjs 3 version)

### ISSUE THREAD

**Issue by sanjeeviraj** [kurkle/chartjs-chart-treemap#37]
I am trying to use chartjs tree map plugin with react-chartjs-2 library (chartjs 3 version), the below is the pervious version usage of treemap

```jsx
import React, { Component } from 'react'
import ChartComponent from 'react-chartjs-2';
import 'chartjs-chart-treemap';

export default class TreeMap extends React.Component {
    
    render() {        
        return (
            <ChartComponent
                {...this.props}
                ref={ref => this.chartInstance = ref && ref.chartInstance}
                type='treemap'
            />
        );
    }
}
```

How to implement it in new version

**Comment by NemeZZiZZ** [comment]
Use canvas, ref for it and useEffect:

`<canvas ref={canvas}></canvas>


  useEffect(() => {
    const ctx = canvas && canvas.current && canvas.current.getContext('2d')
    const chart = new Chart(ctx, options)
`
