### ISSUE TITLE
RTL is not supported

### ISSUE THREAD

**Issue by polinin** [kurkle/chartjs-chart-treemap#4]
Thanks for the implementation!
It would be really helpful to have 'rtl' support for the tree map chart, not only for tooltips and legend.

**Comment by kurkle** [comment]
I'm not really familiar with RTL things, what would you expect changed?
Did you try setting the canvas RTL?

**Comment by polinin** [comment]
Well In RTL is should be reflected. And if labels were left aligned they should be right aligned (that works if setting rtl to canvas but only if you don't calculate labels positions programmatically). But the main idea here is to reflect rectangles:

LTR:
<img width="297" alt="Screen Shot 2020-07-23 at 17 08 21" src="https://user-images.githubusercontent.com/16056921/88296641-a41c3a80-cd07-11ea-9f0b-44bdedc359c3.png">

RTL:
<img width="297" alt="Screen Shot 2020-07-23 at 17 08 46" src="https://user-images.githubusercontent.com/16056921/88296663-aaaab200-cd07-11ea-829c-0b00d15f0f3b.png">

**Comment by kurkle** [comment]
Released 1.0.0-beta.3 with initial RTL support. If its insufficient, please open another issue with specific details.
