### ISSUE TITLE
Wrong tiles placement on certain data

### ISSUE THREAD

**Issue by NemeZZiZZ** [kurkle/chartjs-chart-treemap#42]
https://codepen.io/NemeZZiZZ/pen/VwWpeLO

Actual result:
I got this picture with this data
![image](https://user-images.githubusercontent.com/3491936/132647500-a6f851fa-192e-4a9d-b408-e48ea4cce724.png)
```[346062896.7285156, 4873.543108289924, 2.9610295422558437, 1.3633147804594135, 1.3417739862226647, 1,1, 1, 1, 1]```

Expected result:
Several boxes, even if it small ones

**Comment by kurkle** [comment]
There are several boxes, the small ones are just sub-pixel sized, so not visible. Are you suggesting there should be a minimum size for a box?

**Comment by kurkle** [comment]
Closing due to missing input
