### ISSUE TITLE
function itemSort() in plugins.tooltip do not receive same arg format depending of the browser

### ISSUE THREAD

**Issue by christianheudier** [kurkle/chartjs-chart-treemap#43]
Hi,

I defined the function plugins.tooltip.itemSort(i0, i1). But depending of the browser (firefox vs chromium based): 
 one have more info (like gs, etc...) in i0.raw.gs, the other in i0.raw._data.gs

**Comment by kurkle** [comment]
Could you create a fiddle to reproduce this?

**Comment by kurkle** [comment]
Closing as there was no reproducing fiddle provided
