### ISSUE TITLE
Error when trying to include data labels plugin

### ISSUE THREAD

**Issue by polinin** [kurkle/chartjs-chart-treemap#5]
Was trying to include chartjs-plugin-datalabels to the tree map, but it fails with the error:

`chartjs-plugin-datalabels.js:155 Uncaught TypeError: Cannot read property 'x' of null at orient (chartjs-plugin-datalabels.js:155) at Object.rect [as positioner] (chartjs-plugin-datalabels.js:354) at coordinates (chartjs-plugin-datalabels.js:847) at Object.draw (chartjs-plugin-datalabels.js:1011) at Object.afterDatasetsDraw (chartjs-plugin-datalabels.js:1330) at Object.notify (Chart.js:7537) at Chart.drawDatasets (Chart.js:9422) at Chart.draw (Chart.js:9350) at Chart.render (Chart.js:9304) at Object.callback (Chart.js:1778)`

chartjs-chart-treemap: 0.2.3
charts: 2.9.0

**Comment by kurkle** [comment]
Looks like datalabels expects the elements to contain references to the scales for finding origin.
Treemap is not using any scales (at least not yet), so I'm not sure how hard would it be to make it work.

**Comment by polinin** [comment]
@kurkle yeah, it's probably easier to overwrite `draw` function of Chart to hide captions and implement separate plugin that adds custom labels.

**Comment by kurkle** [comment]
This has been noted on the readme.
