### ISSUE TITLE
Initial animations are not working

### ISSUE THREAD

**Issue by kurkle** [kurkle/chartjs-chart-treemap#58]
### Discussed in https://github.com/kurkle/chartjs-chart-treemap/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **LeifHenriksen** November 16, 2021</sup>
Hi,

I noticed that when using version 1.0.2 that there is no building animation (the animation that plays when the graph spawns), in this code pen you can see it, if you change **chartjs** and **chartjs-chart-treemap** to the old version you get the animation back. https://codepen.io/leifhenriksen/pen/porxqar

The chart in the docs also has no animation : https://chartjs-chart-treemap.pages.dev/usage.html

So my question is, how do I enable the build animation?

Thank you</div>

To me this looks like a regression of some kind.

**Comment by LeifHenriksen** [comment]
Hi, this is a workaround that may be useful for people using an older version with the bug present.
If you follow the following instructions you can get the initial animation back.

```
// Create holder element with display = none

<div id="holder" style="display: none;">
          <canvas id="chart-area"></canvas>
</div>

// Create the chart 

new Chart(...);

// Display the element
document.getElementById(holder).style.display = '';
```
