### ISSUE TITLE
IE11 is not supported

### ISSUE THREAD

**Issue by polinin** [kurkle/chartjs-chart-treemap#6]
The chart is not working in IE11. Version 0.2.3

**Comment by DWboutin** [comment]
Can you provide more infos?

**Comment by polinin** [comment]
It's failing on array extension:

`Syntax error
function flatten(input) {
	const stack = [...input];`

**Comment by DWboutin** [comment]
So, you don't have babel in your project?

**Comment by kurkle** [comment]
To me, IE is history and will not be supported. I might consider a PR though.

**Comment by DWboutin** [comment]
Anyway, it's not even a bug... It's the spread operator who is not recognized by the stack in place.

**Comment by polinin** [comment]
@DWboutin it was pointing to exact file and line number from the lib:) 
Anyway we do polyfill our internal code, for polyfilling modules we need to add to our config, but it's not an option for us because of many dependent projects, so we resolved the issue by copying code to our directory.
