### ISSUE TITLE
How to display value along title in treemap

### ISSUE THREAD

**Issue by sanjeeviraj** [kurkle/chartjs-chart-treemap#7]
![image](https://user-images.githubusercontent.com/14013203/83406030-6697e100-a42b-11ea-8e0a-a19c1ed08c2c.png)

I want to display the label along the value. right now only on hover values of a block is shown in tooltip. Is there any way to show label with value in chart .

**Comment by kurkle** [comment]
I've had that drafted for a while. I'll be pushing a new alpha soon, with that functionality. Meanwhile you can experiment with `next` branch.

I need to draft some docs and I want to update the tool chain & migrato to actions, so will take some days / weeks.

**Comment by kurkle** [comment]
This is available in the latest beta.

**Comment by tshinnick** [comment]
How do you do this?  I tried replicating the [sample ](https://github.com/kurkle/chartjs-chart-treemap/tree/next/samples )files but that's not adding the title to each rectangle.
