### ISSUE TITLE
Add samples of usage with datalabels plugin

### ISSUE THREAD

**Issue by kurkle** [kurkle/chartjs-chart-treemap#75]
This would enable plugins like `chartjs-plugin-zoom` and  `chartjs-plugin-datalabels` to work with treemap.

**Comment by mirzaeianfar** [comment]
Why not do this issue?

**Comment by jhagerman-bc** [comment]
it that could be implemented i would appreciate it for my own project

**Comment by stockiNail** [comment]
`chartjs-plugin-datalabels` should be already supported. Additional tests are needed but a basic example is here:

https://codepen.io/stockinail/pen/oNdBjVG

**Comment by mirzaeianfar** [comment]
How to add the chartjs-plugin-zoom plugin like chartjs-plugin-datalabels plugin?
