### ISSUE TITLE
Children overflow parents when they're narrower than spacing

### ISSUE THREAD

**Issue by imankulov** [kurkle/chartjs-chart-treemap#77]
Hey @kurkle!

I came across an issue in the chartjs-chart-treemap, and I hope you can help me resolve it.

When using groups and non-zero spacing, and when one of the rectangle dimensions is less than the spacing value, child rectangles may overflow their parents.

I reproduced it across all versions between v1.0.0 and v2.0.1. It seems like the version v0.2.3 behaves correctly, hiding the rectangle that's too narrow to show.

If you need more context or any other help with this issue, please let me know. Thank you!

**Codepen samples:**

[chartjs-chart-treemap@2.0.1, chart.js@3.7.0](https://codepen.io/imankulov/pen/oNGpwVm)

<img width="745" alt="chartjs-chart-treemap@2.0.1, chart.js@3.7.0" src="https://user-images.githubusercontent.com/75075/147510770-56eb1c6e-79cd-44fb-ab43-761bb641b58b.png">

---

[chartjs-chart-treemap@0.2.3, chart.js@2.9.4](https://codepen.io/imankulov/pen/gOGoGeK)

<img width="756" alt="chartjs-chart-treemap@0.2.3, chart.js@2.9.4" src="https://user-images.githubusercontent.com/75075/147510773-5ab03f98-d257-4395-9e77-1fd638a41954.png">

**Comment by kurkle** [comment]
Thanks @imankulov, that's a well described bug.

**Comment by imankulov** [comment]
Works like a charm. Thanks a lot for the quick turnaround, Jukka!  ✨ 🍰 ✨
