### ISSUE TITLE
How do I set an onclick listener for a rectangle?

### ISSUE THREAD

**Issue by lukesalamone** [kurkle/chartjs-chart-treemap#8]
I'd like to create an onclick listener for each square but this doesn't seem to work:

```javascript
...
},
options: {
...
    onclick: function(event){
        console.log(event);
    }
...
```

I am able to add onclick listeners for other chart types, for example `line` charts. Is this supported and if not how can I add it? Thanks.

**Comment by kurkle** [comment]
you need to use capital C. `onClick: function(event, active) { console.log(active) }`
