### ISSUE TITLE
Should emit a warning when tooltip positioner is not registered

### ISSUE THREAD

**Issue by kurkle** [kurkle/chartjs-chart-treemap#89]
If Tooltip is not registered before TreemapController, the tooltip positioner is not registered.

https://github.com/kurkle/chartjs-chart-treemap/blob/971f84b935d994dee2ec7ab0c41d2b52a7f46d16/src/controller.js#L372-L386

**Comment by stockiNail** [comment]
@kurkle I think emitting a warning it could a workaround for this issue.
But I was thinking if it could make more sense to add a hook to all "registrables" object in CHART.JS where they can listen when another component has been registered. Something like `notifyRegister` method where the id of the registrable object is passed as argument.

**Comment by kurkle** [comment]
I had similar thoughts, but the registration order should not be important. So maybe emitting error would be best. Also in core for the fill option and missing filler plugin.
