### ISSUE TITLE
Color function is not defined error

### ISSUE THREAD

**Issue by arunreghu** [kurkle/chartjs-chart-treemap#9]
return Color('blue').alpha(alpha).rgbString();
I got an error from this line of code. Where to define that Color function. I am using Vue js and I using this chart by following imports 
import Chart from "chart.js";
import "chartjs-chart-treemap";
new Chart(ctx, {})

**Comment by kurkle** [comment]
You can use `Chart.helpers.color` or any color lib you prefer.
